source 'https://[LICENSEKEY]@github.com/stormideas/storyteller-sdk-podspec.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StorytellerSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StorytellerSampleApp
  pod 'Texture', :git => 'https://github.com/stormideas/Texture.git', :branch => '3.0.0-rc.2'
  pod 'StorytellerSDK',  '~> 4.1.0'
end
